#!/usr/bin/env python
import sys
noden=float(sys.argv[1])
perc=float(sys.argv[2])

d=noden/100*perc
# print "d=",d

pre=0
while 1:
    data=raw_input()
    # Print data
    # if pre!=data.split('\t')[-1]:
    #     pre=data.split('\t')[-1]
    #     print pre

    if int(data.split('\t')[-1])>=d:
        print data.split('\t')[0]
        break
    
