#!/usr/bin/env python
import sys
for line in sys.stdin:
    p=line.split('\t')[0]
    v=line.split('\t')[1]
    if p=="mean":
        print "mean\t",v,
    elif p=="conf95":
        print "conf95\t",v,
    
