#!/bin/bash -x
for i in {1..10}
do
    ./dtnsim -M Monitor::Log -n 100 | ./p-coverage 100 50
done >log-r200-50per
echo -n "$n "
./stats -v log-r200-50per | ./pick-mean-and-conf95 >r200-50per-mean-and-conf95
