#!/bin/bash -x
for n in 10 20 50 100
do
    for i in {1..10}
    do
	./dtnsim -M Monitor::Log -n $n | ./p-coverage $n 90
    done >log-$n-90per
    echo -n "$n "
    ./stats -v log-$n-90per | ./pick-mean-and-conf95 >n$n-90per-mean-and-conf95
done
